services:
  - docker

before_install:
  - docker build -t svetab/vue-blog-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run svetab/vue-blog-test npm run test -- --coverage
  
after_success:
  - docker build -t svetab/vue-blog-client ./client
  - docker build -t svetab/vue-blog-nginx ./nginx
  - docker build -t svetab/vue-blog-server ./server
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push svetab/vue-blog-client
  - docker push svetab/vue-blog-nginx
  - docker push svetab/vue-blog-server

deploy:
  provider: heroku
  app_key: $HEROKU_APP_KEY
  script: 
    - echo "$HEROKU_APP_KEY" | docker login -u "$HEROKU_APP_KEY" --password-stdin registry.heroku.com
    - docker tag svetab/vue-blog-client registry.heroku.com/cliche-blog-engine/web .
    - docker tag svetab/vue-blog-nginx registry.heroku.com/cliche-blog-engine/nginx .
    - docker tag svetab/vue-blog-server registry.heroku.com/cliche-blog-engine/server .
    - docker push registry.heroku.com/cliche-blog-engine/web;
    - docker push registry.heroku.com/cliche-blog-engine/nginx;
    - docker push registry.heroku.com/cliche-blog-engine/server;
    - heroku container:release web nginx server --app cliche-blog-engine

