version: "3"
services:
  client:
    build: 
        dockerfile: Dockerfile.dev
        context: ./client         
    volumes: 
      - /app/node_modules
      - ./client:/app
    ports: 
      - "8080:8080"
  api:    
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    ports:
      - "4000:4000"  
    environment: 
      - MONGO_URL=mongodb://db:27017/clicheblogdb
    depends_on:
      - db
  db:    
    image: mongo
    restart: always       
    ports:
      - "27017:27017"
    
  
  
