version: "3"
services:
  web:
    container_name: bloggi_dev
    restart: always
    build: .
    command: "node starter.js"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
